#!/usr/bin/env bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$CURRENT_DIR/utils.sh"

keybinding=$(get_option_value "@git-worktree-keybinding" "C-g")
popup_width=$(get_option_value "@git-worktree-popup-width" "80")
popup_height=$(get_option_value "@git-worktree-popup-height" "60")

tmux \
  bind-key "$keybinding" \
  display-popup -E -w "$popup_width"% -h "$popup_height"% \
  -d "#{pane_current_path}" \
  "$CURRENT_DIR/git-worktree"
